services:
  cmsusermanagment:
    build:
      context: .
      dockerfile: cmsUserManagment.API/Dockerfile
    depends_on:
      - mysql
      - redis
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=auth;Uid=user;Pwd=alskjdfa@alskdjfAAAb12;"
      Redis__Connection: "redis:6379"
      JwtSettings__Secret: "4ba5b968796f41d8de85d6063fe4929d2cb649594090b9d778e54680ec273341"
      JwtSettings__Issuer: "cms"
      JwtSettings__Audience: "account"
      JwtSettings__ExpiryMinutes: "60"
    ports:
      - "5054:8080"
    command: >
      /bin/bash -c "
        dotnet tool install --global dotnet-ef &&
        export PATH=\"$PATH:/root/.dotnet/tools\" &&
        echo 'Running migrations...' &&
        dotnet ef database update &&
        echo 'Starting API...' &&
        dotnet cmsUserManagment.API.dll
      "



  mysql:
    image: mysql:8.0
    container_name: mysql-auth
    environment:
      MYSQL_DATABASE: auth
      MYSQL_USER: user
      MYSQL_PASSWORD: 'alskjdfa@alskdjfAAAb12'
      MYSQL_ROOT_PASSWORD: 'rootPassword123!'
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mysql-data:
  redis-data:
