version: "3.9"
services:
  cmsusermanagment:
    build:
      context: .
      dockerfile: cmsUserManagment.API/Dockerfile
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=auth;Uid=user;Pwd=alskjdfa@alskdjfAAAb12;"
      Redis__Connection: "redis:6379"
      JwtSettings__Secret: "4ba5b968796f41d8de85d6063fe4929d2cb649594090b9d778e54680ec273341"
      JwtSettings__Issuer: "cms"
      JwtSettings__Audience: "account"
      JwtSettings__ExpiryMinutes: "60"
    ports:
      - "5055:8080"
    networks:
      - cmsusernetwork

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: auth
      MYSQL_USER: user
      MYSQL_PASSWORD: "alskjdfa@alskdjfAAAb12"
      MYSQL_ROOT_PASSWORD: "rootPassword123!"
    ports:
      - "33063:3306" # Host port different
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-user-data:/var/lib/mysql
    networks:
      - cmsusernetwork

  redis:
    image: redis:7
    restart: always
    ports:
      - "6381:6379" # Host port different
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - redis-user-data:/data
    networks:
      - cmsusernetwork

volumes:
  mysql-user-data:
  redis-user-data:

networks:
  cmsusernetwork:
    driver: bridge
