version: "3.9"
services:
  cmsusermanagment:
    build:
      context: .
      dockerfile: cmsUserManagment.API/Dockerfile
    depends_on:
      - mysql
      - redis
    environment:
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=auth;Uid=user;Pwd=alskjdfa@alskdjfAAAb12;"
      Redis__Connection: "redis:6379"
      JwtSettings__Secret: "4ba5b968796f41d8de85d6063fe4929d2cb649594090b9d778e54680ec273341"
      JwtSettings__Issuer: "cms"
      JwtSettings__Audience: "account"
      JwtSettings__ExpiryMinutes: "60"
    ports:
      - "5055:8080"
    networks:
      - cmsusernetwork

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: auth
      MYSQL_USER: user
      MYSQL_PASSWORD: 'alskjdfa@alskdjfAAAb12'
      MYSQL_ROOT_PASSWORD: 'rootPassword123!'
    ports:
      - "33063:3306"   # Host port different
    volumes:
      - mysql-user-data:/var/lib/mysql
    networks:
      - cmsusernetwork

  redis:
    image: redis:7
    ports:
      - "6381:6379"   # Host port different
    volumes:
      - redis-user-data:/data
    networks:
      - cmsusernetwork

volumes:
  mysql-user-data:
  redis-user-data:

networks:
  cmsusernetwork:
    driver: bridge
